#opsin_structure_map.py

import os
import sys
import argparse
import pandas as pd
import numpy as np
import re
import warnings
import urllib.request 
import pathlib

# --- Configuration & Reasoning ---
# PDB files are fixed-width text files (Fortran style). 
# We target the B-factor column (temperature factor), which occupies columns 61-66.
# By replacing this value with the SHAP importance, visualization tools (PyMOL, Chimera, VMD)
# can color the structure by "Temperature", effectively creating a 3D heatmap of ML importance.

def fetch_pdb_from_rcsb(pdb_id, save_dir):
    """
    Downloads a PDB file from the RCSB database if it is not found locally.
    """
    pdb_id = pdb_id.upper()
    url = f"https://files.rcsb.org/download/{pdb_id}.pdb"
    dest_path = os.path.join(save_dir, f"{pdb_id}.pdb")
    
    print(f"   - '{pdb_id}' identified as potential PDB ID. Attempting download from RCSB...")
    print(f"   - Source: {url}")
    
    try:
        urllib.request.urlretrieve(url, dest_path)
        if os.path.exists(dest_path) and os.path.getsize(dest_path) > 0:
            print(f"   - Download successful: {dest_path}")
            return dest_path
        else:
            print(f"   - Download failed (empty file).")
            return None
    except Exception as e:
        print(f"   - Download failed: {e}")
        return None

def parse_shap_csv(shap_csv_path, use_query_positions=False):
    """
    Parses the SHAP analysis CSV generated by optics_shap.py.
    
    Args:
        shap_csv_path: Path to CSV.
        use_query_position: If True, uses the 'query_position' column (Bovine Numbering) as the key.
                           If False, uses the input feature numbering.
    Returns:
        dict: {residue_number (int): aggregated_importance_score (float)}
    """
    try:
        df = pd.read_csv(shap_csv_path)
    except FileNotFoundError:
        raise FileNotFoundError(f"Could not find SHAP data file: {shap_csv_path}")
    
    if not {'shap_effect'}.issubset(df.columns) and not {'abs_shap'}.issubset(df.columns):
        raise ValueError("CSV must contain 'shap_effect' or 'abs_shap' columns.")

    # Determine which column to parse for position info
    if use_query_positions:
        if 'query_position' in df.columns:
            target_col = 'query_position'
            print("   - Using 'query_position' column for mapping .")
        else:
            print("   - WARNING: 'query_position' column not found.\nEither re-run 'optics_shap' to obtain this or opt to map SHAP values to default Bovine Rho structure...")
            raise(ValueError("'query_position' column not found.\nEither re-run 'optics_shap' to obtain this or opt to map SHAP values to default Bovine Rho structure..."))
    else:
        # Fallback to feature/query_position based on what optics_shap usually outputs for 'query_position' argument
        # But specifically here, if use_query_position is False, we likely want the raw feature index input
        target_col = 'reference_position'
        print("   - Using 'reference_position' column for mapping (Reference/Bovine Numbering).")

    importance_map = {}

    for _, row in df.iterrows():
        feature_name = str(row[target_col])
           
        # Regex to find the first sequence of digits (e.g., "123_H" -> 123)
        match = re.search(r'(\d+)', feature_name)
        
        if match or use_query_positions:
            if use_query_positions:
                residue_pos= float(feature_name)
            else:
                residue_pos = int(match.group(1))
            
            if 'abs_shap' in row:
                impact = row['abs_shap']
            else:
                impact = abs(row['shap_effect'])
            
            if residue_pos in importance_map:
                importance_map[residue_pos] += impact
            else:
                importance_map[residue_pos] = impact

    return importance_map

def normalize_importance(importance_map, target_min=0, target_max=100):
    """Normalizes the aggregated importance scores to a 0-100 range."""
    if not importance_map:
        return {}
    
    raw_values = list(importance_map.values())
    min_val = min(raw_values)
    max_val = max(raw_values)
    
    if max_val - min_val == 0:
        return {k: target_max for k in importance_map}

    norm_map = {}
    for pos, val in importance_map.items():
        norm_val = ((val - min_val) / (max_val - min_val)) * (target_max - target_min) + target_min
        norm_map[pos] = norm_val
        
    return norm_map

def map_importance_to_pdb(pdb_input_path, output_path, importance_map, chain_id='A', default_b=0.00):
    """
    Reads a PDB file line-by-line and writes a new file with modified B-factors.
    
    Args:
        chain_id: The specific chain to map to (e.g. 'A'). If None or 'all', maps to all chains.
    """
    
    chain_filter = chain_id.upper() if chain_id and chain_id.lower() != 'all' else None
    
    with open(pdb_input_path, 'r') as f_in, open(output_path, 'w') as f_out:
        for line in f_in:
            if line.startswith("ATOM") or line.startswith("HETATM"):
                try:
                    # PDB Format: Column 22 is chain identifier (index 21 in 0-based string)
                    line_chain = line[21].upper()
                    
                    if chain_filter and line_chain != chain_filter:
                        # Write line unchanged if it's not the target chain
                        f_out.write(line)
                        continue

                    # Columns 23-26: Residue Sequence Number
                    res_seq_str = line[22:26].strip()
                    target_id = int(res_seq_str)
                                    
                    new_b_factor = importance_map.get(target_id, default_b)
                    
                    # Construct new line
                    line_prefix = line[:60]
                    line_suffix = line[66:]
                    b_factor_str = f"{new_b_factor:6.2f}"
                    
                    f_out.write(f"{line_prefix}{b_factor_str}{line_suffix}")
                    
                except ValueError:
                    f_out.write(line)
            else:
                f_out.write(line)

    print(f"Successfully created structural heatmap: {output_path}")

def _execute_mapping(shap_csv, pdb_input, output_dir, use_query_position, chain, suffix=""):
    """
    Internal function to execute the mapping logic for a specific PDB target.
    Allows for multiple calls (e.g. Custom PDB + Bovine Default).
    """
    script_path = pathlib.Path(__file__).resolve()
    wrk_dir = str(script_path.parent).replace('\\', '/')
    
    pdb_file_path = None
    
    # 1. PDB Resolution Logic
    if (not pdb_input or pdb_input.upper() == "1U19"):
        print("   - Using Bovine Rhodopsin (1U19) logic.")
        if pdb_input and pdb_input.upper() == "1U19":
             print("   - 1U19 explicitly requested.")
        else:
             print("   - No PDB provided. Defaulting to 1U19.")
        
        pdb_input = "1U19"
        pdb_file_path = f"{wrk_dir}/data/cached_structures/1U19.pdb"
        
        # When mapping to 1U19, we MUST use reference positions (unless user has pre-mapped SHAP data)
        # Usually, SHAP on query seq -> Query Position. 
        # SHAP on Ref Seq or alignment -> Ref Position (which matches 1U19).
        if use_query_position:
            print('   - Note: Cannot use Query Positions to map onto standard Bovine Rho (1U19).')
            print('   - Switching to Reference Numbering (assuming SHAP file contains reference_position column).')
            use_query_position = False
            
        if not chain: chain = 'A'

    else:
        # Local File or RCSB Download
        if os.path.isfile(pdb_input):
            print(f"1. Using local PDB file: {pdb_input}")
            if not use_query_position:
                print('   - Note: Mapping to custom PDB usually requires mapping Query Positions.')
                print('   - Enabling Use Query Position mode.')
                use_query_position = True
            pdb_file_path = pdb_input
        else:
            if len(pdb_input) == 4 and pdb_input.isalnum():
                print(f"1. '{pdb_input}' is not a local file. Checking online databases...")
                downloaded = fetch_pdb_from_rcsb(pdb_input, output_dir)
                if downloaded:
                    pdb_file_path = downloaded
                    if not use_query_position:
                        print('   - Note: Mapping to fetched PDB usually requires mapping Query Positions.')
                        print('   - Enabling Use Query Position mode.')
                        use_query_position = True
                else:
                    print("   - FATAL: Could not retrieve PDB file.")
                    return None
            else:
                print(f"   - FATAL: File '{pdb_input}' not found and does not look like a valid PDB ID.")
                return None

    base_name = os.path.splitext(os.path.basename(shap_csv))[0]
    base_name = base_name.replace('_shap_analysis', '')
    
    # Add suffix if provided (e.g. "_bovine")
    output_pdb = os.path.join(output_dir, f"{base_name}_structure_heatmap{suffix}.pdb")
    
    print(f"2. Parsing SHAP data from: {os.path.basename(shap_csv)}")
    
    # 1. Parse and Aggregate
    try:
        raw_importance = parse_shap_csv(shap_csv, use_query_positions=use_query_position)
        print(f"   - Found data for {len(raw_importance)} unique residues.")
    except Exception as e:
        print(f"   - Error parsing CSV: {e}")
        return None

    # 2. Normalize
    print(f"3. Normalizing scores to [0-100] scale...")
    norm_importance = normalize_importance(raw_importance)
    
    # 3. Map to PDB
    print(f"4. Mapping to template structure: {os.path.basename(pdb_file_path)}")
    print(f"   - Chain Target: {chain if chain else 'All'}")
    if use_query_position:
        print(f"   - Mode: Query Position Mapping (Target Sequence Numbering)")
    else:
        print(f"   - Mode: True Position Mapping (Reference/Bovine Numbering)")
    
    try:
        map_importance_to_pdb(pdb_file_path, output_pdb, norm_importance, chain_id=chain)
        
        # PyMOL Script
        pymol_script = os.path.join(output_dir, f"visualize_{base_name}{suffix}.pml")
        with open(pymol_script, 'w') as pml:
            pml.write(f"load {os.path.basename(output_pdb)}\n")
            pml.write("hide everything\n")
            pml.write("show cartoon\n")
            pml.write("spectrum b, blue_white_red, minimum=0, maximum=100\n")
            pml.write("ramp_new scale, none, [0, 50, 100], [blue, white, red]\n")
            pml.write("bg_color white\n")
            pml.write(f"# NOTE: B-factors now represent ML Feature Importance (0=Low, 100=High)\n")
        
        print(f"5. Bonus: Created PyMOL visualization script at {pymol_script}")
        return output_pdb
        
    except Exception as e:
        print(f"   - Error writing PDB: {e}")
        return None

def run_structural_mapping(shap_csv, pdb_input=None, output_dir=None, use_query_position=False, chain='A', map_to_bovine_also=False):
    """
    Main orchestration function.
    
    Args:
        shap_csv (str): Path to CSV data.
        pdb_input (str): Path to local PDB OR a PDB ID. If None, defaults to '1U19'.
        output_dir (str): Destination for outputs.
        use_query_position (bool): Map to query/target sequence if True (requires SHAP CSV to have query_position column), otherwise, map to Bovine.
        chain (str): Chain to map to (Default 'A').
        map_to_bovine_also (bool): If True, runs a second pass mapping to 1U19 using reference numbering.
    """
    if output_dir is None:
        output_dir = os.path.dirname(shap_csv)
    
    if not os.path.isdir(output_dir):
        os.makedirs(output_dir, exist_ok=True)

    print(f"\n--- Starting Structural Importance Mapping ---")
    
    primary_pdb = None
    
    # Pass 1: Primary Requested PDB
    primary_pdb = _execute_mapping(
        shap_csv, 
        pdb_input, 
        output_dir, 
        use_query_position, 
        chain
    )
    
    # Pass 2: Secondary Bovine Mapping (if requested and primary wasn't already 1U19)
    if map_to_bovine_also:
        is_already_bovine = (pdb_input and pdb_input.upper() == "1U19") or (not pdb_input)
        
        if not is_already_bovine:
            print(f"\n--- Starting Secondary Mapping: Bovine Rhodopsin (1U19) ---")
            _execute_mapping(
                shap_csv,
                "1U19",
                output_dir,
                use_query_position=False, # Force Reference Numbering for Bovine
                chain='A', # Usually Chain A for 1U19
                suffix="_1U19_ref"
            )
        else:
            print("\n--- Secondary Mapping Skipped: Primary selection was already Bovine/1U19 ---")

    return primary_pdb

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Map OPTICS SHAP importance values onto a 3D PDB structure.")
    
    parser.add_argument("-s", "--shap_csv", help="Path to the SHAP analysis CSV file", required=True)
    parser.add_argument("-p", "--pdb_file", help="Path to PDB file or ID. Default: 1U19", default=None)
    parser.add_argument("-o", "--output_dir", help="Output directory", default=None)
    parser.add_argument("--chain", help="Chain to map to. Default: A", type=str, default='A')
    parser.add_argument("--use_query_position", help="Map using Reference/Bovine numbering column in CSV", action="store_true")
    parser.add_argument("--map_bovine_also", help="Also generate a map for standard Bovine (1U19)", action="store_true")

    args = parser.parse_args()
    
    run_structural_mapping(
        args.shap_csv, args.pdb_file, args.output_dir, 
        args.use_query_position, args.chain, args.map_bovine_also
    )