#opsin_structure_map.py

import os
import sys
import argparse
import pandas as pd
import numpy as np
import re
import warnings
import urllib.request # Added to support online PDB fetching

# --- Configuration & Reasoning ---
# PDB files are fixed-width text files (Fortran style). 
# We target the B-factor column (temperature factor), which occupies columns 61-66.
# By replacing this value with the SHAP importance, visualization tools (PyMOL, Chimera, VMD)
# can color the structure by "Temperature", effectively creating a 3D heatmap of ML importance.

def fetch_pdb_from_rcsb(pdb_id, save_dir):
    """
    Downloads a PDB file from the RCSB database if it is not found locally.
    
    Args:
        pdb_id (str): The 4-character PDB accession code (e.g., '1U19').
        save_dir (str): Directory to save the downloaded file.
        
    Returns:
        str: Path to the downloaded file, or None if failed.
    """
    pdb_id = pdb_id.upper()
    url = f"https://files.rcsb.org/download/{pdb_id}.pdb"
    dest_path = os.path.join(save_dir, f"{pdb_id}.pdb")
    
    print(f"   - '{pdb_id}' identified as potential PDB ID. Attempting download from RCSB...")
    print(f"   - Source: {url}")
    
    try:
        # User-agent is sometimes required by strict servers, though RCSB is usually lenient.
        # using standard urllib.request.urlretrieve is the simplest method for "No Heavy Dependencies"
        urllib.request.urlretrieve(url, dest_path)
        
        # Verify download wasn't an HTML error page (basic check)
        if os.path.exists(dest_path) and os.path.getsize(dest_path) > 0:
            print(f"   - Download successful: {dest_path}")
            return dest_path
        else:
            print(f"   - Download failed (empty file).")
            return None
            
    except Exception as e:
        print(f"   - Download failed: {e}")
        return None

def parse_shap_csv(shap_csv_path, encoding_method='aa_prop'):
    """
    Parses the SHAP analysis CSV generated by optics_shap.py.
    
    Logic:
    1. Reads the CSV containing 'feature' and 'shap_effect' (or 'abs_shap').
    2. Extracts the residue position from the feature name.
       - Expected AA_PROP format: "P123_Hydrophobicity" -> Pos 123
       - Expected ONE_HOT format: "123_A" or "A123_..." -> Pos 123
    3. Aggregates values: A single residue may have multiple features (mass, charge, etc.).
       We sum the ABSOLUTE SHAP values to determine total importance of that site.
    
    Returns:
        dict: {residue_number (int): aggregated_importance_score (float)}
    """
    try:
        df = pd.read_csv(shap_csv_path)
    except FileNotFoundError:
        raise FileNotFoundError(f"Could not find SHAP data file: {shap_csv_path}")
    
    # Validation: Ensure required columns exist
    # usage of 'shap_effect' allows us to calculate magnitude ourselves
    if 'true_position' in df.columns:
        required_cols = {'true_position', 'shap_effect'}
    else:
        required_cols = {'feature', 'shap_effect'}

    if not required_cols.issubset(df.columns):
        # Fallback to abs_shap if shap_effect isn't there, or error out
        if 'abs_shap' in df.columns and 'feature' in df.columns:
            pass # We are good
        else:
            raise ValueError(f"CSV must contain columns: {required_cols}")

    importance_map = {}

    for _, row in df.iterrows():
        
        if 'true_position' in df.columns:
            feature_name = str(row['true_position'])
        else:
            feature_name = str(row['feature'])

        
        # --- Feature Name Parsing Logic ---
        # We need to extract the numeric position from strings like "P123_H1" or "123_A".
        # We use Regex to find the first sequence of digits.
        match = re.search(r'(\d+)', feature_name)
        
        if match:
            residue_pos = int(match.group(1))
            
            # Get magnitude of importance (absolute value)
            # We care about impact, not direction (red/blue shift) for the structure map
            if 'abs_shap' in row:
                impact = row['abs_shap']
            else:
                impact = abs(row['shap_effect'])
            
            # Aggregate: Add to existing total for this residue
            if residue_pos in importance_map:
                importance_map[residue_pos] += impact
            else:
                importance_map[residue_pos] = impact
        else:
            # Skip features that don't map to a specific residue (e.g., global descriptors if any)
            continue

    return importance_map

def normalize_importance(importance_map, target_min=0, target_max=100):
    """
    Normalizes the aggregated importance scores to a 0-100 range (Standard B-factor range).
    This makes visualization in tools like PyMOL much easier (e.g., 'spectrum b').
    """
    if not importance_map:
        return {}
    
    raw_values = list(importance_map.values())
    min_val = min(raw_values)
    max_val = max(raw_values)
    
    # Avoid division by zero if all scores are identical
    if max_val - min_val == 0:
        return {k: target_max for k in importance_map}

    norm_map = {}
    for pos, val in importance_map.items():
        # Min-Max normalization formula
        norm_val = ((val - min_val) / (max_val - min_val)) * (target_max - target_min) + target_min
        norm_map[pos] = norm_val
        
    return norm_map

def map_importance_to_pdb(pdb_input_path, output_path, importance_map, offset=0, default_b=0.00):
    """
    Reads a PDB file line-by-line and writes a new file with modified B-factors.
    
    Args:
        pdb_input_path: Path to template PDB.
        output_path: Path to save the new PDB.
        importance_map: Dict of {residue_id: score}.
        offset: Integer to adjust PDB numbering vs Alignment numbering.
                (e.g., if PDB starts at 1 but Alignment starts at 20, offset is -19).
        default_b: Value to use if a residue is in PDB but not in SHAP data.
    """
    
    with open(pdb_input_path, 'r') as f_in, open(output_path, 'w') as f_out:
        for line in f_in:
            # We only modify lines starting with ATOM or HETATM
            if line.startswith("ATOM") or line.startswith("HETATM"):
                try:
                    # --- PDB Column Parsing (Standard v3.3) ---
                    # Columns 23-26: Residue Sequence Number (Integer)
                    # Columns 61-66: Temperature Factor (Real 6.2)
                    
                    res_seq_str = line[22:26].strip()
                    pdb_res_id = int(res_seq_str)
                    
                    # Calculate the corresponding ID in our SHAP map
                    # Logic: Alignment_ID = PDB_ID + Offset
                    # (Users might need to tweak offset depending on their specific alignment)
                    target_id = pdb_res_id + offset
                    
                    # Get new B-factor value
                    new_b_factor = importance_map.get(target_id, default_b)
                    
                    # --- Reconstruction ---
                    # Slice the line to preserve exact formatting (PDBs are strict)
                    # Pre-B-factor part (Cols 1-60)
                    line_prefix = line[:60]
                    # Post-B-factor part (Cols 67-End)
                    line_suffix = line[66:]
                    
                    # Format new B-factor as string (width 6, 2 decimal places)
                    b_factor_str = f"{new_b_factor:6.2f}"
                    
                    f_out.write(f"{line_prefix}{b_factor_str}{line_suffix}")
                    
                except ValueError:
                    # If parsing fails (e.g. insertion codes), write line unchanged
                    f_out.write(line)
            else:
                # Write header/footer lines unchanged
                f_out.write(line)

    print(f"Successfully created structural heatmap: {output_path}")


def run_structural_mapping(shap_csv, pdb_input, output_dir=None, offset=0):
    """
    Main orchestration function. Can be imported by GUI.
    
    Args:
        shap_csv (str): Path to CSV data.
        pdb_input (str): Path to local PDB OR a PDB ID (e.g. "1U19").
        output_dir (str): Destination for outputs.
        offset (int): alignment offset.
    """
    if output_dir is None:
        output_dir = os.path.dirname(shap_csv)
    
    # Ensure output dir exists
    if not os.path.isdir(output_dir):
        os.makedirs(output_dir, exist_ok=True)
        
    print(f"\n--- Starting Structural Importance Mapping ---")
    
    # --- PDB Resolution Logic ---
    pdb_file_path = pdb_input
    
    if os.path.isfile(pdb_input):
        print(f"1. Using local PDB file: {pdb_input}")
    else:
        # Check if input looks like a PDB ID (4 chars, alphanumeric)
        # This allows user to just type "1u19" instead of a path
        if len(pdb_input) == 4 and pdb_input.isalnum():
            print(f"1. '{pdb_input}' is not a local file. Checking online databases...")
            downloaded = fetch_pdb_from_rcsb(pdb_input, output_dir)
            if downloaded:
                pdb_file_path = downloaded
            else:
                print("   - FATAL: Could not retrieve PDB file.")
                return None
        else:
             print(f"   - FATAL: File '{pdb_input}' not found and does not look like a valid PDB ID.")
             return None

    # Generate output filename based on the SHAP csv name
    base_name = os.path.splitext(os.path.basename(shap_csv))[0]
    base_name = base_name.replace('_shap_analysis', '')
    output_pdb = os.path.join(output_dir, f"{base_name}_structure_heatmap.pdb")
    
    print(f"2. Parsing SHAP data from: {os.path.basename(shap_csv)}")
    
    # 1. Parse and Aggregate
    try:
        raw_importance = parse_shap_csv(shap_csv)
        print(f"   - Found data for {len(raw_importance)} unique residues.")
    except Exception as e:
        print(f"   - Error parsing CSV: {e}")
        return None

    # 2. Normalize
    print(f"3. Normalizing scores to [0-100] scale...")
    norm_importance = normalize_importance(raw_importance)
    
    # 3. Map to PDB
    print(f"4. Mapping to template structure: {os.path.basename(pdb_file_path)}")
    print(f"   - Applying alignment offset: {offset}")
    
    try:
        map_importance_to_pdb(pdb_file_path, output_pdb, norm_importance, offset=offset)
        
        # Create a simple PyMOL script
        pymol_script = os.path.join(output_dir, f"visualize_{base_name}.pml")
        with open(pymol_script, 'w') as pml:
            pml.write(f"load {os.path.basename(output_pdb)}\n")
            pml.write("hide everything\n")
            pml.write("show cartoon\n")
            pml.write("spectrum b, blue_white_red, minimum=0, maximum=100\n")
            pml.write("ramp_new scale, none, [0, 50, 100], [blue, white, red]\n")
            pml.write("bg_color white\n")
            pml.write(f"# NOTE: B-factors now represent ML Feature Importance (0=Low, 100=High)\n")
        
        print(f"5. Bonus: Created PyMOL visualization script at {pymol_script}")
        return output_pdb
        
    except Exception as e:
        print(f"   - Error writing PDB: {e}")
        return None

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Map OPTICS SHAP importance values onto a 3D PDB structure.")
    
    parser.add_argument("-s", "--shap_csv", 
                        help="Path to the SHAP analysis CSV file (generated by optics_shap.py)", 
                        required=True)
    parser.add_argument("-p", "--pdb_file", 
                        help="Path to a local PDB file OR a 4-letter PDB ID (e.g., '1U19') to fetch from RCSB.", 
                        required=True)
    parser.add_argument("-o", "--output_dir", 
                        help="Directory to save the output PDB. Defaults to SHAP file directory.", 
                        default=None)
    parser.add_argument("--offset", 
                        help="Integer offset to align SHAP positions with PDB numbering. (Default: 0)", 
                        type=int, 
                        default=0)

    args = parser.parse_args()
    
    run_structural_mapping(args.shap_csv, args.pdb_file, args.output_dir, args.offset)