#opsin_structure_map.py

import os
import sys
import argparse
import pandas as pd
import numpy as np
import re
import warnings
import urllib.request 
import pathlib

# --- Configuration & Reasoning ---
# PDB files are fixed-width text files (Fortran style). 
# We target the B-factor column (temperature factor), which occupies columns 61-66.
# By replacing this value with the SHAP importance, visualization tools (PyMOL, Chimera, VMD)
# can color the structure by "Temperature", effectively creating a 3D heatmap of ML importance.

def fetch_pdb_from_rcsb(pdb_id, save_dir):
    """
    Downloads a PDB file from the RCSB database if it is not found locally.
    """
    pdb_id = pdb_id.upper()
    url = f"https://files.rcsb.org/download/{pdb_id}.pdb"
    dest_path = os.path.join(save_dir, f"{pdb_id}.pdb")
    
    print(f"   - '{pdb_id}' identified as potential PDB ID. Attempting download from RCSB...")
    print(f"   - Source: {url}")
    
    try:
        urllib.request.urlretrieve(url, dest_path)
        if os.path.exists(dest_path) and os.path.getsize(dest_path) > 0:
            print(f"   - Download successful: {dest_path}")
            return dest_path
        else:
            print(f"   - Download failed (empty file).")
            return None
    except Exception as e:
        print(f"   - Download failed: {e}")
        return None

def parse_shap_csv(shap_csv_path, use_query_positions=False, comp_target=1):
    """
    Parses the SHAP analysis CSV generated by optics_shap.py (both individual or comparison).
    
    Args:
        shap_csv_path: Path to CSV.
        use_query_positions: If True, uses the 'query_position' or 'query_position_{n}' column.
                           If False, uses the input feature numbering.
        comp_target: If mapping a comparison CSV with query_positions, choose Seq 1 or 2 (Default 1).
    Returns:
        dict: {residue_number (int): aggregated_importance_score (float)}
    """
    try:
        df = pd.read_csv(shap_csv_path)
    except FileNotFoundError:
        raise FileNotFoundError(f"Could not find SHAP data file: {shap_csv_path}")
    
    # Automatically detect if this is a comparison or single SHAP CSV
    has_single = {'shap_effect'}.issubset(df.columns) or {'abs_shap'}.issubset(df.columns)
    has_comp = {'shap_difference'}.issubset(df.columns) or {'abs_shap_diff'}.issubset(df.columns)

    if not has_single and not has_comp:
        raise ValueError("CSV must contain 'shap_effect', 'abs_shap', 'shap_difference', or 'abs_shap_diff' columns.")
        
    is_comparison = has_comp

    # Determine which column to parse for position info
    if use_query_positions:
        if 'query_position' in df.columns:
            target_col = 'query_position'
            print("   - Using 'query_position' column for mapping.")
        elif f'query_position_{comp_target}' in df.columns:
            target_col = f'query_position_{comp_target}'
            print(f"   - Using 'query_position_{comp_target}' column for mapping (Pairwise Comparison mode).")
        else:
            print("   - WARNING: 'query_position' column not found.\nEither re-run 'optics_shap' to obtain this or opt to map SHAP values to default Bovine Rho structure...")
            raise(ValueError(f"Could not find query position columns. Make sure your CSV was generated with optics_shap mapping features enabled."))
    else:
        # Fallback to feature/query_position based on what optics_shap usually outputs
        target_col = 'reference_position'
        print("   - Using 'reference_position' column for mapping (Reference/Bovine Numbering).")

    importance_map = {}

    for _, row in df.iterrows():
        feature_name = str(row[target_col])
        if feature_name in ['NA', 'nan', 'NaN', 'None']:
            continue
           
        # Regex to find the first sequence of digits (e.g., "123_H" -> 123)
        match = re.search(r'(\d+)', feature_name)
        
        if match or use_query_positions:
            if use_query_positions:
                try:
                    residue_pos = float(feature_name)
                except ValueError:
                    continue # Skip if entirely invalid
            else:
                residue_pos = int(match.group(1))
            
            # Determine appropriate impact measure based on file type
            if is_comparison:
                impact = row['abs_shap_diff'] if 'abs_shap_diff' in df.columns else abs(row['shap_difference'])
            else:
                impact = row['abs_shap'] if 'abs_shap' in df.columns else abs(row['shap_effect'])
            
            if residue_pos in importance_map:
                importance_map[residue_pos] += impact
            else:
                importance_map[residue_pos] = impact

    return importance_map, is_comparison

def normalize_importance(importance_map, target_min=0, target_max=100):
    """Normalizes the aggregated importance scores to a 0-100 range."""
    if not importance_map:
        return {}
    
    raw_values = list(importance_map.values())
    min_val = min(raw_values)
    max_val = max(raw_values)
    
    if max_val - min_val == 0:
        return {k: target_max for k in importance_map}

    norm_map = {}
    for pos, val in importance_map.items():
        norm_val = ((val - min_val) / (max_val - min_val)) * (target_max - target_min) + target_min
        norm_map[pos] = norm_val
        
    return norm_map

def map_importance_to_pdb(pdb_input_path, output_path, importance_map, chain_id='A', default_b=0.00):
    """
    Reads a PDB file line-by-line and writes a new file with modified B-factors.
    
    Args:
        chain_id: The specific chain to map to (e.g. 'A'). If None or 'all', maps to all chains.
    """
    
    chain_filter = chain_id.upper() if chain_id and chain_id.lower() != 'all' else None
    
    with open(pdb_input_path, 'r') as f_in, open(output_path, 'w') as f_out:
        for line in f_in:
            if line.startswith("ATOM") or line.startswith("HETATM"):
                try:
                    # PDB Format: Column 22 is chain identifier (index 21 in 0-based string)
                    line_chain = line[21].upper()
                    
                    if chain_filter and line_chain != chain_filter:
                        # Write line unchanged if it's not the target chain
                        f_out.write(line)
                        continue

                    # Columns 23-26: Residue Sequence Number
                    res_seq_str = line[22:26].strip()
                    target_id = int(res_seq_str)
                                    
                    new_b_factor = importance_map.get(target_id, default_b)
                    
                    # Construct new line
                    line_prefix = line[:60]
                    line_suffix = line[66:]
                    b_factor_str = f"{new_b_factor:6.2f}"
                    
                    f_out.write(f"{line_prefix}{b_factor_str}{line_suffix}")
                    
                except ValueError:
                    f_out.write(line)
            else:
                f_out.write(line)

    print(f"Successfully created structural heatmap: {output_path}")

def _execute_mapping(shap_csv, pdb_input, output_dir, use_query_position, chain, suffix="", comp_target=1, top_n_labels=0, software='pymol'):
    """
    Internal function to execute the mapping logic for a specific PDB target.
    Allows for multiple calls (e.g. Custom PDB + Bovine Default).
    """
    script_path = pathlib.Path(__file__).resolve()
    wrk_dir = str(script_path.parent).replace('\\', '/')
    
    pdb_file_path = None
    
    # 1. PDB Resolution Logic
    if (not pdb_input or pdb_input.upper() == "1U19"):
        print("   - Using Bovine Rhodopsin (1U19) logic.")
        if pdb_input and pdb_input.upper() == "1U19":
             print("   - 1U19 explicitly requested.")
        else:
             print("   - No PDB provided. Defaulting to 1U19.")
        
        pdb_input = "1U19"
        pdb_file_path = f"{wrk_dir}/data/cached_structures/1U19.pdb"
        
        # When mapping to 1U19, we MUST use reference positions (unless user has pre-mapped SHAP data)
        # Usually, SHAP on query seq -> Query Position. 
        # SHAP on Ref Seq or alignment -> Ref Position (which matches 1U19).
        if use_query_position:
            print('   - Note: Cannot use Query Positions to map onto standard Bovine Rho (1U19).')
            print('   - Switching to Reference Numbering (assuming SHAP file contains reference_position column).')
            use_query_position = False
            
        if not chain: chain = 'A'

    else:
        # Local File or RCSB Download
        if os.path.isfile(pdb_input):
            print(f"1. Using local PDB file: {pdb_input}")
            if not use_query_position:
                print('   - Note: Mapping to custom PDB usually requires mapping Query Positions.')
                print('   - Enabling Use Query Position mode.')
                use_query_position = True
            pdb_file_path = pdb_input
        else:
            if len(pdb_input) == 4 and pdb_input.isalnum():
                print(f"1. '{pdb_input}' is not a local file. Checking online databases...")
                downloaded = fetch_pdb_from_rcsb(pdb_input, output_dir)
                if downloaded:
                    pdb_file_path = downloaded
                    if not use_query_position:
                        print('   - Note: Mapping to fetched PDB usually requires mapping Query Positions.')
                        print('   - Enabling Use Query Position mode.')
                        use_query_position = True
                else:
                    print("   - FATAL: Could not retrieve PDB file.")
                    return None
            else:
                print(f"   - FATAL: File '{pdb_input}' not found and does not look like a valid PDB ID.")
                return None

    print(f"2. Parsing SHAP data from: {os.path.basename(shap_csv)}")
    
    # 1. Parse and Aggregate
    try:
        raw_importance, is_comparison = parse_shap_csv(shap_csv, use_query_positions=use_query_position, comp_target=comp_target)
        print(f"   - Found data for {len(raw_importance)} unique residues.")
    except Exception as e:
        print(f"   - Error parsing CSV: {e}")
        return None
    
    base_name = os.path.splitext(os.path.basename(pdb_input))[0]
    base_name = base_name.replace('_shap_analysis', '').replace('_shap_data', '')
    if is_comparison:
        comparison_note = '_comparison'
    else:
        comparison_note = ''
    # Add suffix if provided (e.g. "_bovine")
    if suffix != '_1U19_ref':
        output_pdb = os.path.join(output_dir, f"{base_name}_shap{comparison_note}_mapped{suffix}.pdb")
    else:
        output_pdb = os.path.join(output_dir, f"{base_name}_ref_shap_mapped.pdb")

    

    # 2. Normalize
    print(f"3. Normalizing scores to [0-100] scale...")
    norm_importance = normalize_importance(raw_importance)
    
    # 3. Map to PDB
    print(f"4. Mapping to template structure: {os.path.basename(pdb_file_path)}")
    print(f"   - Chain Target: {chain if chain else 'All'}")
    if use_query_position:
        print(f"   - Mode: Query Position Mapping (Target Sequence Numbering)")
    else:
        print(f"   - Mode: True Position Mapping (Reference/Bovine Numbering)")
    
    try:
        map_importance_to_pdb(pdb_file_path, output_pdb, norm_importance, chain_id=chain)
        
        # Identify Top N sites for labeling
        top_sites = []
        if top_n_labels > 0 and norm_importance:
            sorted_sites = sorted(norm_importance.items(), key=lambda item: item[1], reverse=True)
            top_sites = [site for site, val in sorted_sites[:top_n_labels]]
        
        # Visualization Script Generation
        software = software.lower()
        if software == 'pymol':
            if suffix != '_1U19_ref':
                pymol_script = os.path.join(output_dir, f"shap{comparison_note}_map_viz_{base_name}{suffix}.pml")
            else:
                pymol_script = os.path.join(output_dir, f"shap{comparison_note}_map_viz_{base_name}_ref.pml")

            with open(pymol_script, 'w') as pml:
                pml.write(f"load {os.path.basename(output_pdb)}\n")
                pml.write("hide everything\n")
                pml.write(f"show cartoon, chain {chain}\n")
                pml.write(f"spectrum b, blue_white_red, selection=chain {chain}, minimum=0, maximum=100\n")
                pml.write("ramp_new scale, none, [0, 50, 100], [blue, white, red]\n")
                pml.write("bg_color black\n")
                pml.write(f"# NOTE: B-factors now represent ML Feature Importance (0=Low, 100=High)\n")
                
                if top_sites:
                    pml.write("\n# --- Top SHAP Site Labels ---\n")
                    for site in top_sites:
                        sel_name = f"top_site_{site}"
                        pml.write(f"select {sel_name}, chain {chain} and resi {site}\n")
                        pml.write(f"label {sel_name} and n. ca, '{site}'\n")
                    pml.write("set label_color, white\n")
                    pml.write("set label_position, (2, 2, 2)\n")
                    pml.write("set label_size, 20\n")
                    pml.write("deselect\n")
                    
            print(f"5. Bonus: Created PyMOL visualization script at {pymol_script}")
        
        elif software == 'chimerax':
            if suffix != '_1U19_ref':
                cxc_script = os.path.join(output_dir, f"shap_map_viz_{base_name}{suffix}.cxc")
            else:
                cxc_script = os.path.join(output_dir, f"shap_map_viz_{base_name}_ref.cxc")

            with open(cxc_script, 'w') as cxc:
                cxc.write(f"camera ortho\nopen {os.path.basename(output_pdb)}\nzoom 0.75\nmove x -5\n")
                cxc.write("hide atoms\n")
                cxc.write("hide cartoons\n")
                cxc.write(f"show /{chain} cartoons\nlight gentle\ngraphics silhouettes true width 1.5\n")
                cxc.write(f"color byattribute bfactor /{chain} palette #5ab4ac:#f5f5f5:#ef8a62 range 0,100\n")
                cxc.write(f"set bgColor black\n")
                cxc.write("# Delete the next line if you don't wont the surface loaded...\n")
                cxc.write(f"surface /{chain}\ntransparency 95 target s\n")
                cxc.write("key #5ab4ac:0 #f5f5f5:50 #ef8a62:100 pos 0.85,0.2 size 0.035,0.55 justification left labelOffset 5\n")
                cxc.write("2dlab text 'SHAP Importance' size 30 xpos .79 ypos .145\n")
                cxc.write(f"# NOTE: B-factors now represent ML Feature Importance (0=Low, 100=High)\n")
                
                if top_sites:
                    cxc.write("\n# --- Top SHAP Site Labels ---\n")
                    for site in top_sites:
                        sel = f"/{chain}:{site:.0f}"
                        cxc.write(f"label {sel} text '{site:.0f}'\n")
                        cxc.write(f"show {sel} atoms\n")
                    cxc.write("label color white\n")
                    cxc.write("label height 3.0\n")
                    
            print(f"5. Bonus: Created ChimeraX visualization script at {cxc_script}")
        
        return output_pdb
        
    except Exception as e:
        print(f"   - Error writing PDB: {e}")
        return None

def run_structural_mapping(shap_csv, pdb_input=None, output_dir=None, use_query_position=False, chain='A', map_to_bovine_also=False, comp_target='1', top_n_labels=0, software='chimerax'):
    """
    Main orchestration function.
    
    Args:
        shap_csv (str): Path to CSV data.
        pdb_input (str/list): Path to local PDB OR a PDB ID. Can be comma-separated string for two structures. If None, defaults to '1U19'.
        output_dir (str): Destination for outputs.
        use_query_position (bool): Map to query/target sequence if True (requires SHAP CSV to have query_position column), otherwise, map to Bovine.
        chain (str): Chain to map to (Default 'A').
        map_to_bovine_also (bool): If True, runs a second pass mapping to 1U19 using reference numbering.
        comp_target (str): Target sequence if using a comparison CSV and mapping via query positions ('1', '2', or 'both').
        top_n_labels (int): Number of top SHAP sites to annotate with text labels.
        software (str): 'pymol' or 'chimerax' script output format.
    """
    if output_dir is None:
        output_dir = os.path.dirname(shap_csv)
    
    if not os.path.isdir(output_dir):
        os.makedirs(output_dir, exist_ok=True)

    print(f"\n--- Starting Structural Importance Mapping ---")
    
    primary_pdb = None
    
    # Process PDB Inputs into a list
    if isinstance(pdb_input, str):
        pdbs = [p.strip() for p in pdb_input.split(',')]
    elif isinstance(pdb_input, list):
        pdbs = pdb_input
    elif pdb_input is None or pdb_input == "":
        pdbs = ["1U19"]
    else:
        pdbs = [str(pdb_input)]
        
    if not pdbs or pdbs[0] == "":
        pdbs = ["1U19"]
    
    # Determine comparison targets to run
    comp_targets_to_run = []
    if use_query_position and str(comp_target).lower() == 'both':
        comp_targets_to_run = [1, 2]
    else:
        try:
            comp_targets_to_run = [int(comp_target)]
        except ValueError:
            comp_targets_to_run = [1]
            
    # Pass 1: Primary Requested PDB (loops if 'both' is selected)
    for ct in comp_targets_to_run:
        pdb_idx = ct - 1
        current_pdb = pdbs[pdb_idx] if pdb_idx < len(pdbs) and pdbs[pdb_idx] != "" else pdbs[0]
        
        suffix_ct = f"_seq{ct}" if len(comp_targets_to_run) > 1 else ""
        primary_pdb = _execute_mapping(
            shap_csv, 
            current_pdb, 
            output_dir, 
            use_query_position, 
            chain,
            suffix=suffix_ct,
            comp_target=ct,
            top_n_labels=top_n_labels,
            software=software
        )
    
    # Pass 2: Secondary Bovine Mapping (if requested and primary wasn't already 1U19)
    if map_to_bovine_also:
        is_already_bovine = (pdbs[0].upper() == "1U19") and len(pdbs) == 1
        
        if not is_already_bovine:
            print(f"\n--- Starting Secondary Mapping: Bovine Rhodopsin (1U19) ---")
            _execute_mapping(
                shap_csv,
                "1U19",
                output_dir,
                use_query_position=False, # Force Reference Numbering for Bovine
                chain='A', # Usually Chain A for 1U19
                suffix="_1U19_ref",
                comp_target=1, # Doesn't matter for Reference Numbering
                top_n_labels=top_n_labels,
                software=software
            )
        else:
            print("\n--- Secondary Mapping Skipped: Primary selection was already Bovine/1U19 ---")

    return primary_pdb

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Map OPTICS SHAP importance values onto a 3D PDB structure.")
    
    parser.add_argument("-s", "--shap_csv", help="Path to the SHAP analysis CSV file (Single or Comparison)", required=True)
    parser.add_argument("-p", "--pdb_file", help="Path to PDB file(s) or ID(s). Can provide two comma-separated paths if mapping 'both' sequences.", default=None, type=str)
    parser.add_argument("-o", "--output_dir", help="Output directory", default=None)
    parser.add_argument("--chain", help="Chain to map to. Default: A", type=str, default='A')
    parser.add_argument("--use_query_position", help="Map using target sequence numbering column in CSV", action="store_true")
    parser.add_argument("--map_bovine_also", help="Also generate a map for standard Bovine (1U19)", action="store_true")
    parser.add_argument("--comp_target", help="If using a comparison CSV with query positions, choose which sequence's numbering to use ('1', '2', or 'both').", type=str, default="1")
    parser.add_argument("--top_n_labels", help="Number of top SHAP sites to label in the visualization script.", type=int, default=0)
    parser.add_argument("--software", help="Target software for visualization script ('pymol' or 'chimerax').", type=str, default="chimerax", choices=["pymol", "chimerax"])

    args = parser.parse_args()
    
    run_structural_mapping(
        args.shap_csv, args.pdb_file, args.output_dir, 
        args.use_query_position, args.chain, args.map_bovine_also, 
        args.comp_target, args.top_n_labels, args.software
    )